services:
  # Servi√ßo do Banco de Dados MySQL
  db:
    image: mysql:8.0.32
    container_name: vemprofut-db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - vemprofut-db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # criar o usuario automaticamente dentro do container MySQL

    # üëá Healthcheck para garantir que o MySQL est√° pronto
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  # Servi√ßo da API VemProFut
  api:
    build: .
    container_name: vemprofut-api
    env_file:
      - .env
    restart: on-failure
    depends_on:
       db:
         condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # Conex√£o com MySQL com URL do banco dentro da rede Docker
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&connectTimeout=30000&socketTimeout=60000

      # Flyway - tenta reconectar v√°rias vezes enquanto MySQL inicializa
      SPRING_FLYWAY_CONNECT_RETRIES: 10
      SPRING_FLYWAY_CONNECT_RETRIES_INTERVAL: 5s

      # Auth0 - Dessa forma, o Spring vai ler direto do ambiente, sem precisar de '.properties' para mapear
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI: ${AUTH0_ISSUER}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH0_ISSUER}

      # Forca Spring Boot a ouvir em todas interfaces (necessario para Docker)
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      SERVER_SERVLET_SESSION_COOKIE_SECURE: false

volumes:
  vemprofut-db-data: #  garante que os dados do DB n√£o sejam perdidos quando o cont√™iner do MySQL for reiniciado.
