services:
  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: vemprofut-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - vemprofut-db-data:/var/lib/mysql

  # Serviço da API VemProFut
  api:
    build: .
    container_name: vemprofut-api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  vemprofut-db-data: #  garante que os dados do banco de dados não sejam perdidos quando o contêiner do MySQL for reiniciado.
